version = 1

[[annotations]]
path = [
    "Tests/SpeziSchedulerTests/Resources/**",
    "Tests/SpeziSchedulerUITests/__Snapshots__/**"
]
SPDX-FileCopyrightText = "2025 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"
